# configure_motd_with_vars.yml
---
- name: Configure MOTD using external variables
  hosts: all
  become: yes
  vars_files:
    - vars/motd_vars.yml

  tasks:
    - name: Create custom MOTD with variables
      ansible.builtin.template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
   
    - name: Reload SSH service to apply new MOTD
      ansible.builtin.systemd:
        name: ssh
        state: reloaded

    - name: Verify MOTD is readable
      ansible.builtin.command: cat /etc/motd
      register: motd_check
    
    - name: Display current MOTD
      ansible.builtin.debug:
        msg: "Текущий MOTD:\n{{ motd_check.stdout }}"